<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-07 at 06:41:45.
 */
class JitroTest extends PHPUnit_Framework_TestCase
{
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Jitro::AddKey
     * @expectedException InvalidArgumentException
     * @todo   Implement testAddKey().
     */
    public function testAddKey()
    {
        //ok values
        Jitro::AddKey("a",array("a","b"), "GET");
        Jitro::AddKey("b",array("a","b"), "POST");
        Jitro::AddKey("a",array("ALL"), "GET");
        
        //Not ok
        Jitro::AddKey("c",array(), "GET");
        Jitro::AddKey("c",array("a"), "BLAAH");




        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Jitro::Get
     * @todo   Implement testGet().
     */
    public function testGet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Jitro::GetValidatedKeys
     * @todo   Implement testGetValidatedKeys().
     */
    public function testGetValidatedKeys()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Jitro::GetIgnoredKeys
     * @todo   Implement testGetIgnoredKeys().
     */
    public function testGetIgnoredKeys()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Jitro::Authenticate
     * @todo   Implement testAuthenticate().
     */
    public function testAuthenticate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
